/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppShopRouteImport } from './routes/_app.shop'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPracticeRouteImport } from './routes/_app.practice'
import { Route as AppGameMapRouteImport } from './routes/_app.game-map'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppModulesIdRouteImport } from './routes/_app.modules.$id'

const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppGameMapRoute = AppGameMapRouteImport.update({
  id: '/game-map',
  path: '/game-map',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesIdRoute = AppModulesIdRouteImport.update({
  id: '/modules/$id',
  path: '/modules/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/placement': typeof PlacementRoute
  '/dashboard': typeof AppDashboardRoute
  '/game-map': typeof AppGameMapRoute
  '/practice': typeof AppPracticeRoute
  '/profile': typeof AppProfileRoute
  '/shop': typeof AppShopRoute
  '/modules/$id': typeof AppModulesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/placement': typeof PlacementRoute
  '/dashboard': typeof AppDashboardRoute
  '/game-map': typeof AppGameMapRoute
  '/practice': typeof AppPracticeRoute
  '/profile': typeof AppProfileRoute
  '/shop': typeof AppShopRoute
  '/modules/$id': typeof AppModulesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/placement': typeof PlacementRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/game-map': typeof AppGameMapRoute
  '/_app/practice': typeof AppPracticeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/shop': typeof AppShopRoute
  '/_app/modules/$id': typeof AppModulesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/placement'
    | '/dashboard'
    | '/game-map'
    | '/practice'
    | '/profile'
    | '/shop'
    | '/modules/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/placement'
    | '/dashboard'
    | '/game-map'
    | '/practice'
    | '/profile'
    | '/shop'
    | '/modules/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/placement'
    | '/_app/dashboard'
    | '/_app/game-map'
    | '/_app/practice'
    | '/_app/profile'
    | '/_app/shop'
    | '/_app/modules/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlacementRoute: typeof PlacementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice': {
      id: '/_app/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/game-map': {
      id: '/_app/game-map'
      path: '/game-map'
      fullPath: '/game-map'
      preLoaderRoute: typeof AppGameMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules/$id': {
      id: '/_app/modules/$id'
      path: '/modules/$id'
      fullPath: '/modules/$id'
      preLoaderRoute: typeof AppModulesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppGameMapRoute: typeof AppGameMapRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppShopRoute: typeof AppShopRoute
  AppModulesIdRoute: typeof AppModulesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppGameMapRoute: AppGameMapRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppProfileRoute: AppProfileRoute,
  AppShopRoute: AppShopRoute,
  AppModulesIdRoute: AppModulesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlacementRoute: PlacementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
